#!/bin/bash

set -e

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

pacman -Qqen >"$BASE_DIR/backup.qqen"
pacman -Qqem >"$BASE_DIR/backup.qqem"

echo ":: Backup of package list was updated and saved to: $BASE_DIR"
