#!/usr/bin/env bash

set -e

BASE_DIR="__INSTALL_DIR__"

pacman -Qqen >"$BASE_DIR/backup.qqen"
pacman -Qqem >"$BASE_DIR/backup.qqem"

echo ":: Backup of package list was updated and saved to: $BASE_DIR"
